<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SecureOSBApp/SecureOSB/SecureDocuments" name="SecureDocuments-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SecureDocuments.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SecureOSBApp/SecureOSB/SecureDocuments"/>
    <wsdl:binding name="SecureDocuments_ptt-binding" type="sec:SecureDocuments_ptt" xmlns:sec="http://xmlns.oracle.com/pcbpel/adapter/db/SecureOSBApp/SecureOSB/SecureDocuments">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SecureDocumentsSelect">
            <soap:operation soapAction="SecureDocumentsSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>